// generated by stringer -type=itemType; DO NOT EDIT

package parse

import "fmt"

const _itemType_name = "itemErroritemBoolitemEOFitemNameitemQueryitemLeftCurlyitemRightCurlyitemLeftParenitemRightParenitemNumberitemColonitemCommaitemStringitemKeyworditemDotitemNil"

var _itemType_index = [...]uint8{0, 9, 17, 24, 32, 41, 54, 68, 81, 95, 105, 114, 123, 133, 144, 151, 158}

func (i itemType) String() string {
	if i < 0 || i+1 >= itemType(len(_itemType_index)) {
		return fmt.Sprintf("itemType(%d)", i)
	}
	return _itemType_name[_itemType_index[i]:_itemType_index[i+1]]
}
