// generated by stringer -type=itemType; DO NOT EDIT

package ast

import "fmt"

const _itemType_name = "itemErroritemEOFitemNameitemVariableitemLeftCurlyitemRightCurlyitemLeftParenitemRightParenitemLeftSquareitemRightSquareitemAtSignitemColonitemCommaitemDotitemNilitemEqualitemIntValueitemStringValueitemFloatValueitemKeyworditemQueryitemMutationitemFragmentitemEllipsesitemTrueitemFalseitemOnitemIntTypeitemFloatTypeitemBooleanTypeitemEnumTypeitemArrayTypeitemObjectType"

var _itemType_index = [...]uint16{0, 9, 16, 24, 36, 49, 63, 76, 90, 104, 119, 129, 138, 147, 154, 161, 170, 182, 197, 211, 222, 231, 243, 255, 267, 275, 284, 290, 301, 314, 329, 341, 354, 368}

func (i itemType) String() string {
	if i < 0 || i+1 >= itemType(len(_itemType_index)) {
		return fmt.Sprintf("itemType(%d)", i)
	}
	return _itemType_name[_itemType_index[i]:_itemType_index[i+1]]
}
