// generated by stringer -type=itemType; DO NOT EDIT

package grammar

import "fmt"

const _itemType_name = "itemErroritemEOFitemNameitemVariableitemLeftCurlyitemRightCurlyitemLeftParenitemRightParenitemAtSignitemColonitemCommaitemDotitemNilitemIntValueitemStringValueitemFloatValueitemKeyworditemQueryitemMutationitemFragmentitemEllipsesitemTrueitemFalseitemOnitemIntTypeitemFloatTypeitemBooleanTypeitemEnumTypeitemArrayTypeitemObjectType"

var _itemType_index = [...]uint16{0, 9, 16, 24, 36, 49, 63, 76, 90, 100, 109, 118, 125, 132, 144, 159, 173, 184, 193, 205, 217, 229, 237, 246, 252, 263, 276, 291, 303, 316, 330}

func (i itemType) String() string {
	if i < 0 || i+1 >= itemType(len(_itemType_index)) {
		return fmt.Sprintf("itemType(%d)", i)
	}
	return _itemType_name[_itemType_index[i]:_itemType_index[i+1]]
}
